/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratoriosiu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author SEBAS
 */
public class MAESTROS_CURSOS extends javax.swing.JInternalFrame {
    private static String db = "universidad";
    private static String user = "root";
    private static String password = "Cagada1234";
    private static String host = "localhost";
    private static String server = "jdbc:mysql://"+ host + "/" +db; 
    /**
     * Creates new form ALUMNOS_MAESTROS
     */
    public MAESTROS_CURSOS() {
        initComponents();
        this.setTitle(" MANTENIMIENTO MAESTROS CURSOS Sebastian Moreira  ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreCurso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        label_status = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnVaciar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtNombreMaestros = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_buscarCurso = new javax.swing.JTextField();
        btnBuscarCurso = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_buscarMaestros = new javax.swing.JTextField();
        btnBuscarAlunos = new javax.swing.JButton();
        btnBuscarNombreCurso = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        txtNombreCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCursoActionPerformed(evt);
            }
        });

        jLabel1.setText("NOMBRE MAESTROS:");

        label_status.setText("Estado");

        btnGuardar.setText("Registrar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setText("NOMBRE CURSO:");

        btnVaciar.setText("Vaciar Campos");
        btnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton1.setText("ALUMNOS CURSOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Ingresa el código de la curso: ");

        btnBuscarCurso.setText("Buscar");
        btnBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCursoActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingresa el código del maestros: ");

        btnBuscarAlunos.setText("Buscar");
        btnBuscarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlunosActionPerformed(evt);
            }
        });

        btnBuscarNombreCurso.setText("Buscar Nombre Curso");
        btnBuscarNombreCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreMaestros, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnVaciar)
                                .addGap(18, 18, 18)
                                .addComponent(label_status))
                            .addComponent(btnBuscarNombreCurso)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_buscarMaestros, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarAlunos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_buscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarCurso)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCurso)
                    .addComponent(txt_buscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarAlunos)
                    .addComponent(txt_buscarMaestros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarNombreCurso))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreMaestros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_status)
                            .addComponent(btnVaciar))))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCursoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //Codigo que permite insertar registros en al base de datos
        try{
            //local host y el nombre de la base de datos y la contraseña
            Connection cn = DriverManager.getConnection(server, user, password);
            //Esto permitirá el insert
            PreparedStatement pst = cn.prepareStatement("insert into cursoMaestro values(?,?,?)");

            //El primer parametro de cada setString es cada ?
            pst.setString(1, "0");
            pst.setString(2, txtNombreCurso.getText().trim());
            pst.setString(3, txtNombreMaestros.getText().trim());
            

            pst.executeUpdate();

            txtNombreCurso.setText("");
            txtNombreMaestros.setText("");
           
                    txtNombreCurso.setText("");
        txtNombreMaestros.setText("");
       
        txt_buscarCurso.setText("");
        txt_buscarMaestros.setText("");

            label_status.setText("Registro exitoso.");
        }catch (Exception e){

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarActionPerformed
        // TODO add your handling code here:
        txtNombreCurso.setText("");
        txtNombreMaestros.setText("");
       
        txt_buscarCurso.setText("");
        txt_buscarMaestros.setText("");
    }//GEN-LAST:event_btnVaciarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Codigo que permite actualizar registros en la base de datos
        try {
            String ID = txtNombreCurso.getText().trim();

            Connection cn = DriverManager.getConnection(server, user, password);
            PreparedStatement pst = cn.prepareStatement("update cursoMaestro set nombreCursos = ?, nombreMaestros = ?  nombreCurso = " + ID);

            pst.setString(1, txtNombreCurso.getText().trim());
            pst.setString(2, txtNombreMaestros.getText().trim());
            

            pst.executeUpdate();

            label_status.setText("Modificación exitosa.");

            txtNombreCurso.setText("");
            txtNombreMaestros.setText("");
         
            txt_buscarCurso.setText("");
            txt_buscarMaestros.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Codigo que permite borrar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(server, user, password);
            PreparedStatement pst = cn.prepareStatement("delete from cursoMaestros where nombreCurso = ?");

            pst.setString(1, txtNombreCurso.getText().trim());
            pst.executeUpdate();

            txtNombreCurso.setText("");
            txtNombreMaestros.setText("");
           
            txt_buscarCurso.setText("");
            label_status.setText("Registro eliminado.");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarNombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreCursoActionPerformed
        // TODO add your handling code here:
         try{
            //local host y el nombre de la base de datos y la contraseñña
            Connection cn = DriverManager.getConnection(server, user, password);
            //Esto permitirá el buscar registro a traves del ID
            PreparedStatement pst = cn.prepareStatement("select * from cursos where codigoCursos = ?");
            //El parametro 1 es de que solo un ? esta llenando y entra lo del txt
            pst.setString(1, txt_buscarCurso.getText().trim());

            //El result del query, lo que ira a traer
            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                txtNombreCurso.setText(rs.getString("nombreCursos"));
                
               

                JOptionPane.showMessageDialog(null, "Facultad encontrada.");
            } else {
                JOptionPane.showMessageDialog(null, "Facultad no encontrada.");
            }

        }catch (Exception e){

        }
    }//GEN-LAST:event_btnBuscarNombreCursoActionPerformed

    private void btnBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCursoActionPerformed
        // TODO add your handling code here:
         try{
            //local host y el nombre de la base de datos y la contraseñña
            Connection cn = DriverManager.getConnection(server, user, password);
            //Esto permitirá el buscar registro a traves del ID
            PreparedStatement pst = cn.prepareStatement("select * from cursos where codigoCursos = ?");
            //El parametro 1 es de que solo un ? esta llenando y entra lo del txt
            pst.setString(1, txt_buscarCurso.getText().trim());

            //El result del query, lo que ira a traer
            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                txtNombreCurso.setText(rs.getString("nombreCursos"));
                
               

                JOptionPane.showMessageDialog(null, "Curso encontrad0.");
            } else {
                JOptionPane.showMessageDialog(null, "Curso no encontrada.");
            }

        }catch (Exception e){

        }
    }//GEN-LAST:event_btnBuscarCursoActionPerformed

    private void btnBuscarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlunosActionPerformed
        // TODO add your handling code here:
          try{
            //local host y el nombre de la base de datos y la contraseñña
            Connection cn = DriverManager.getConnection(server, user, password);
            //Esto permitirá el buscar registro a traves del ID
            PreparedStatement pst = cn.prepareStatement("select * from maestros where codigoMaestros = ?");
            //El parametro 1 es de que solo un ? esta llenando y entra lo del txt
            pst.setString(1, txt_buscarMaestros.getText().trim());

            //El result del query, lo que ira a traer
            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                txtNombreMaestros.setText(rs.getString("nombreMaestros"));
                
               

                JOptionPane.showMessageDialog(null, "Maestro encontrada.");
            } else {
                JOptionPane.showMessageDialog(null, "Maestro no encontrada.");
            }

        }catch (Exception e){

        }
    }//GEN-LAST:event_btnBuscarAlunosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAlunos;
    private javax.swing.JButton btnBuscarCurso;
    private javax.swing.JButton btnBuscarNombreCurso;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVaciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label_status;
    private javax.swing.JTextField txtNombreCurso;
    private javax.swing.JTextField txtNombreMaestros;
    private javax.swing.JTextField txt_buscarCurso;
    private javax.swing.JTextField txt_buscarMaestros;
    // End of variables declaration//GEN-END:variables
}
